# Changes here will be overwritten by Copier
_src_path: /Users/andytwoods/PycharmProjects/DjangoAppliku/template
db_type: postgresql_18
email_backend: console
media_storage: none
package_manager: uv
project_slug: testapp1
python_version: '3.13'
task_runner: none
use_sentry: 'false'
web_server: gunicorn
